---
- name: Deploy Docker images
  hosts: master
  become: yes

  vars:
    app_image_name: allezon
    app_image_file: /tmp/allezon.tar
    balancer_image_name: my-proxy
    balancer_container_name: my_proxy_container

  tasks:
    - name: Save app image to a tar file
      command: docker save -o {{ app_image_file }} {{ app_image_name }}

    - name: Ensure the app image tar file is readable by all users
      file:
        path: "{{ app_image_file }}"
        owner: root
        group: root
        mode: '0644'

    - name: Copy app image to nodes
      copy:
        src: "{{ app_image_file }}"
        dest: "{{ app_image_file }}"
      delegate_to: "{{ item }}"
      with_items: "{{ groups['nodes'] }}"

    - name: Remove existing load balancer container if it exists
      command: docker rm -f {{ balancer_container_name }}
      ignore_errors: yes

    - name: Run the load balancer container
      command: docker run -d --network=host --privileged --name {{ balancer_container_name }} {{ balancer_image_name }}

- name: Load Docker image and run app container on all nodes
  hosts: nodes
  become: yes

  vars:
    image_name: allezon
    image_file: /tmp/allezon.tar
    container_name: allezon_container

  tasks:
    - name: Remove existing image if it exists
      command: docker image rm -f {{ image_name }}
      ignore_errors: yes

    - name: Load Docker image from tar file
      command: docker load -i {{ image_file }}

    - name: Remove existing container if it exists
      command: docker rm -f {{ container_name }}
      ignore_errors: yes

    - name: Run Docker container
      command: docker run -d --network=host --name {{ container_name }} {{ image_name }}
